# Generated by Django 5.0.7 on 2024-07-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', 'handle_null_tracks_in_userplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.track'),
        ),
    ]
