# Generated by Django 5.0.7 on 2024-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.TextField(),
        ),
    ]
