# Generated by Django 5.0.7 on 2024-07-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_alter_userplaylist_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.track'),
        ),
    ]
