# Generated by Django 5.0.7 on 2024-07-28 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_userplaylist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplaylist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.track'),
        ),
        migrations.AlterUniqueTogether(
            name='userplaylist',
            unique_together={('user', 'playlist_name', 'track')},
        ),
    ]
