# Generated by Django 5.0.7 on 2024-07-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_alter_userplaylist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.track'),
        ),
    ]
