# Generated by Django 5.0.7 on 2024-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='spotify_access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spotify_refresh_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
